add_subdirectory(kpm_sm)
add_subdirectory(mac_sm)
add_subdirectory(rlc_sm)
add_subdirectory(pdcp_sm)
add_subdirectory(slice_sm)
add_subdirectory(tc_sm)
add_subdirectory(gtp_sm)
add_subdirectory(rc_sm)
add_subdirectory(zxc_sm)
add_subdirectory(enb_conf_sm)
add_subdirectory(counters_sm)
add_subdirectory(sib1_sm)
add_subdirectory(sib2_sm)
add_subdirectory(uetrace_sm)
add_subdirectory(rr_sm)
